### ISSUE TITLE
Don't stick with alphabet

### ISSUE THREAD

**Issue by gobzateloon** [mejia-b/Side-Projects#1]
When you decrypting symbols you will face big problems 

live decryption and encryption https://gobzateloon.github.io/

**Comment by mejia-b** [comment]
Yes I understand and you make a good point of it. I could of coded this differently by using the ASCII Table. But in a Caesars cipher the message is only the alphabet letters no other characters and the key will be a be number from 1-26. This is my understanding from my Network Security class. Correct me if im wrong.

**Comment by gobzateloon** [comment]
LOL 😄  i didn't know what is Caesars cipher until you say.  thank for the theory 😃 
**My suggestions**
- use **replace** method. (It was faster than replacing letter by letter)
- **don't** ever use an one method for different process. (keep it mind)
- when you working with method use **return**. 
- always use **OO concept**. (Because that class file might help you later)
i don't say always go through with my suggestions. just trust me its lot useful for later

**Comment by mejia-b** [comment]
Yes thank you for all your great suggestions!  I usually don't do my methods in such a way but it was just something I coded pretty fast and I should of spent more time. I will have to come back to it some other time and edit this code.
